name: cgroup

on:
  push:

jobs:
  win-run:
    runs-on: ${{ matrix.os }}  ${{ matrix.lbl }} 
    strategy:
      matrix:
        os: [  self-hosted  ]
        lbl: [  r1, r2, r3 ]  
    steps:
      - run: echo hello  
