name: cgroup

on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: df
        run: |
          df -h
          docker system df
          docker run nvidia/cuda:10.2-cudnn7-devel-centos7
          df -h
          docker system df
  check_cgroup:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - name: Install environment
        run: |
          df -h
          
