name: cgroup

on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: cgroup
        run: |
          docker run ubuntu:latest
          cd /sys/fs/cgroup/systemd/actions_job
          ls

          
