name: cgroup

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkout-and-check-formatting:
    runs-on: ubuntu-latest

    steps:
    - name: check cgroup
      run: |
        cd /sys/fs/cgroup 
        ls
